name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test on Node.js
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15, 14, 12.7]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test on node.js ${{ matrix.node-version }}
        run: yarn test
